### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by juanantoniofigueroa** [desenvolvedorindie/yii2-metronic#1]
C:\xampp\htdocs\wfcreations> composer require wfcreations/yii2-metronic "*"
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wfcreations/yii2-metronic could not be found in any version, there may be a typo in the pack
age name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, deleting ./composer.json.

**Comment by desenvolvedorindie** [comment]
Try add

``` json
"minimum-stability": "dev"
```

In composer.json file
