### ISSUE TITLE
composer error 2

### ISSUE THREAD

**Issue by juanantoniofigueroa** [desenvolvedorindie/yii2-metronic#2]
C:\xampp\htdocs\wfcreations> composer require wfcreations/yii2-metronic "@dev"
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wfcreations/yii2-metronic @dev -> satisfiable by wfcreations/yii2-metronic[dev-master].
    - wfcreations/yii2-metronic dev-master requires wfcreations/yii2-simple-line-icons \* -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, deleting ./composer.json.

**Comment by desenvolvedorindie** [comment]
duplicated
