### ISSUE TITLE
wfcreations/yii2-asset-legacy dev-master requires bower-asset/excanvas * -> no matching package found.

### ISSUE THREAD

**Issue by juanantoniofigueroa** [desenvolvedorindie/yii2-metronic#3]
C:\xampp\htdocs\yii2-metronic-master> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wfcreations/yii2-asset-legacy @dev -> satisfiable by wfcreations/yii2-asset-legacy[dev-ma
ster].
    - wfcreations/yii2-asset-legacy dev-master requires bower-asset/excanvas \* -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by desenvolvedorindie** [comment]
Try before composer require, use:

`composer global require "fxp/composer-asset-plugin:1.0.3"`
